global_costmap:
    global_frame: map
    static_map: true
    update_frequency: 1.0
    publish_frequency: 1.0
    raytrace_range: 2.0
    resolution: 0.05
    z_resolution: 0.2
    z_voxels: 10
    inflation:
      cost_scaling_factor:  3.0  # Exponential rate at which the obstacle cost drops off (default: 10). Must be chosen so that the cost value is > 0 at robot's circumscribed radius.
      inflation_radius:     0.6  # Max. distance from an obstacle at which costs are incurred for planning paths. Must be > robot's circumscribed radius.

    # plugins are loaded via costmap_global_params_plugins_[mapping|planning].yaml
GlobalPlanner:        
   allow_unknown: true